<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Subject;
use App\Models\SubjectMap;

class SubjectMappingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subjectMappings = [
            ['employo' => 'Accounting', 'teachers_on_net' => 'Accounting', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Business Administration', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Agricultural Science', 'teachers_on_net' => 'Agriculture', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Arabic', 'teachers_on_net' => 'Arabic', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Armenian', 'teachers_on_net' => 'Armenian', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Art and Visual Art', 'teachers_on_net' => 'Visual Art', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Arts Technician', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'Biology', 'teachers_on_net' => 'Biology', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Boarding Supervisor', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Student Services'],
            ['employo' => 'Head of Boarding House', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Boarding', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Building and Construction', 'teachers_on_net' => 'Building and Construction', 'seek' => 'Public Transport & Taxi Services'],
            ['employo' => 'Bus Driver', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Business Manager', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Business', 'teachers_on_net' => 'Business Studies', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Canteen / Tuck Shop', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Kitchen & Sandwich Hands'],
            ['employo' => 'Chaplan', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Chemistry', 'teachers_on_net' => 'Chemistry', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Chinese / Mandarin', 'teachers_on_net' => 'Chinese', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Civics and Citizenship', 'teachers_on_net' => 'Society and Culture', 'seek' => 'Management - Schools'],
            ['employo' => 'Classical Studies', 'teachers_on_net' => 'Ancient History', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Classroom Assistant - Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Classroom Assistant - Secondary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Cleaners', 'teachers_on_net' => 'Cleaning Services', 'seek' => 'Cleaning Services'],
            ['employo' => 'Coach', 'teachers_on_net' => 'Coaching & Instruction', 'seek' => 'Coaching & Instruction'],
            ['employo' => 'Commerce', 'teachers_on_net' => 'Commerce', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Counsellor - Careers', 'teachers_on_net' => 'Counsellors/ Psychologists', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Counsellor - Guidance', 'teachers_on_net' => 'Counsellors/Psychologists', 'seek' => 'Student Services'],
            ['employo' => 'Creative and Digital Media', 'teachers_on_net' => 'Media Arts', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Daily Organiser', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Dance', 'teachers_on_net' => 'Dance', 'seek' => 'Not Applicable'],
            ['employo' => 'Deputy Principal', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Design Technology - Engineering Studies', 'teachers_on_net' => 'Engineering Studies', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Design Technology - Food', 'teachers_on_net' => 'Food Technology/ Nutrition', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Design Technology - Materials', 'teachers_on_net' => 'Building and Construction', 'seek' => 'Management - Schools'],
            ['employo' => 'Design Technology - Textiles', 'teachers_on_net' => 'Textiles', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'Drama', 'teachers_on_net' => 'Drama', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'EAL', 'teachers_on_net' => 'ESL/EALD', 'seek' => 'Teaching -Secondary'],
            ['employo' => 'Early Childhood (0-5yo)', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Early Childhood'],
            ['employo' => 'Earth and Environmental Science', 'teachers_on_net' => 'Earth and Environmental Science', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Economics', 'teachers_on_net' => 'Economics', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Engineering', 'teachers_on_net' => 'Engineering Studies', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'English Language', 'teachers_on_net' => 'ESL/EALD', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'English', 'teachers_on_net' => 'English', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Enrolments Officer', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Equine Studies', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Finance and Payroll', 'teachers_on_net' => 'Financial Accounting & Controllers', 'seek' => 'Management - Schools'],
            ['employo' => 'French', 'teachers_on_net' => 'French', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Furnishing', 'teachers_on_net' => 'Furnishing', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'General Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'General Science', 'teachers_on_net' => 'Science', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Geography', 'teachers_on_net' => 'Geography', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'German', 'teachers_on_net' => 'German', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Gifted and Talented', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'Global Politics', 'teachers_on_net' => 'Politics', 'seek' => 'Management - Schools'],
            ['employo' => 'Graphics', 'teachers_on_net' => 'Graphics', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Grounds & Maintenance', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Gradening & Landscaping'],
            ['employo' => 'Head of Department - Art', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Design Technology', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - English', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - HPE', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Humanities', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - IT', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - LOTE', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Mathematics', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Music', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Performing Arts', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - RE', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Science', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - Sport', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department - VET/VM', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of Department- SEN', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of School - Junior', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of School - Middle', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Head of School - Senior', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Health', 'teachers_on_net' => 'Health', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Hebrew', 'teachers_on_net' => 'Hebrew', 'seek' => 'Teaching - Primary'],
            ['employo' => 'History', 'teachers_on_net' => 'History', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Hospitality', 'teachers_on_net' => 'Hospitality', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Human Resources', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Consulting & Generalist HR'],
            ['employo' => 'Humanities', 'teachers_on_net' => 'Humanities', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Indigenous Education', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Indonesian', 'teachers_on_net' => 'Indonesian', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Information Technology', 'teachers_on_net' => 'Information Processes and Technology', 'seek' => 'Help Desk & IT Support'],
            ['employo' => 'Instrumental Music', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'IT - Digital Technology', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'IT - Systems Technology', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'IT Technician', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Italian', 'teachers_on_net' => 'Italian', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Japanese', 'teachers_on_net' => 'Japanese', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Laboratory Technician', 'teachers_on_net' => 'Laboratory & Technical Services', 'seek' => 'Laboratory & Technical Services'],
            ['employo' => 'Latin', 'teachers_on_net' => 'Latin', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Legal Studies', 'teachers_on_net' => 'Legal Studies', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Library/Information Services', 'teachers_on_net' => 'Library Services & Information Management', 'seek' => 'Library Services & Information Management'],
            ['employo' => 'Literacy - Primary', 'teachers_on_net' => 'Literacy', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Literacy - Secondary', 'teachers_on_net' => 'Literacy', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Lower Primary (R-2)', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Marketing', 'teachers_on_net' => 'Marketing Communications', 'seek' => 'Marketing Communications'],
            ['employo' => 'Mathematics', 'teachers_on_net' => 'Mathematics', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Media', 'teachers_on_net' => 'Media Arts', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Middle Primary (3-4)', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Middle School Mathematics', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Music Industry', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Music', 'teachers_on_net' => 'Music', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Music', 'teachers_on_net' => 'Music', 'seek' => 'Teaching - Primary'],
            ['employo' => 'OSHC', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Childcare & Outside School Hours Care'],
            ['employo' => 'Outdoor and Environmental Studies', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'PA / EA', 'teachers_on_net' => 'PA, EA & Secretarial', 'seek' => 'PA, EA & Secretarial'],
            ['employo' => 'Performing Arts - Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Personal Development Skills (PDS)', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Philosophy and Ethics', 'teachers_on_net' => 'Philosophy', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Physical Education', 'teachers_on_net' => 'Physical Education', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Physics', 'teachers_on_net' => 'Physics', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Primary Art', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Primary Mathematics', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Primary Physical Education', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Principal', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Psychology', 'teachers_on_net' => 'Psychology', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'RE - Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Religious Education', 'teachers_on_net' => 'Religious Studies/Studies of Religion', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'School Nurse', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Nursing - General Medical & Surgical'],
            ['employo' => 'SEN Assistant', 'teachers_on_net' => 'Teaching Aides & Special Needs', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'SEN - Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'SEN - Secondary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching Aides & Special Needs'],
            ['employo' => 'Spanish', 'teachers_on_net' => 'Spanish', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Spanish', 'teachers_on_net' => 'Spanish', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Sport and Recreation', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'STEM - Primary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'STEM - Secondary', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'TAS Teacher', 'teachers_on_net' => 'TAS', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Teacher Librarian - Primary', 'teachers_on_net' => 'Library Services & Information Management', 'seek' => 'Library Services & Information Management'],
            ['employo' => 'Teacher Librarian - Secondary', 'teachers_on_net' => 'Library Services & Information Management', 'seek' => 'Library Services & Information Management'],
            ['employo' => 'Timetabling', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Travel and Tourism', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Tourism'],
            ['employo' => 'Upper Primary (5-6)', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Work Related Skills', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Farmhand', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Farm Labour'],
            ['employo' => 'Islamic Studies', 'teachers_on_net' => 'Islamic Studies', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Jewish Studies', 'teachers_on_net' => 'Jewish Studies', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Kindergarten Teacher', 'teachers_on_net' => 'Early Childhood Teacher', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Centre Director', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Early Childhood Teacher', 'teachers_on_net' => 'Early Childhood Teacher', 'seek' => 'Teaching - Primary'],
            ['employo' => 'Childcare Assistant', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Childcare & Outside School Hours Care'],
            ['employo' => 'Assistant Centre Manager', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Centre Manager', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Education Leader', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Management - Schools'],
            ['employo' => 'Educator', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Lead Educator', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Secondary'],
            ['employo' => 'Trainee - Educators', 'teachers_on_net' => 'Not Applicable', 'seek' => 'Teaching - Early Childhood']
        ];

        foreach ($subjectMappings as $map) {
            $subject = Subject::create(['name' => $map['employo']]);

            SubjectMap::create([
                'subject_id' => $subject->id,
                'ton' => $map['teachers_on_net'],
                'ehq' => '',
                'seek' => $map['seek']
            ]);
        }
    }
}
